/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_ft_mynative_MyNativeHello */

#ifndef _Included_com_ft_mynative_MyNativeHello
#define _Included_com_ft_mynative_MyNativeHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ft_mynative_MyNativeHello
 * Method:    fun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ft_mynative_MyNativeHello_fun
  (JNIEnv *, jobject);

/*
 * Class:     com_ft_mynative_MyNativeHello
 * Method:    fun2
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ft_mynative_MyNativeHello_fun2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ft_mynative_MyNativeHello
 * Method:    fun3
 * Signature: ([Ljava/lang/Integer;)V
 */
JNIEXPORT void JNICALL Java_com_ft_mynative_MyNativeHello_fun3
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
